version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: postgres_banking_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_finance_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./Banking_databse.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data_insertion.sql:/docker-entrypoint-initdb.d/02-users.sql
      - ./grant_privileges_to_user.sql:/docker-entrypoint-initdb.d/01-grant_privileges.sql